#!/bin/bash
LINT=$(which swiftlint) 
if [[ -e "${LINT}" ]]; then 
    echo "SwiftLint Start..."
else 
    echo "SwiftLint does not exist, download from https://github.com/realm/SwiftLint" 
    exit 1
fi
$LINT lint --quiet