#!/bin/bash
#
# Automatically adds branch name to every commit message.
#
value=`cat $1`
type="$( cut -d ':' -f 1 <<< "$value" )"
contains=$(echo ${typeList[@]} | grep -o type | wc -w)
if [ contains -eq 0 ]; then
    return 1
fi

NAME=$(git branch | grep '*' | sed 's/* //') 
echo "$NAME"': '$(cat "$1") > "$1"